sonar.projectKey=proacademic-frontend
sonar.projectName=ProAcademic Frontend
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/pro-academic/lcov.info
sonar.javascript.lcov.reportPaths=coverage/pro-academic/lcov.info